name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [edited, opened, reopened]
    branches: [ develop ]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: npm install
    
    - name: Run Linting
      run: npm run lint
    
    # - name: FTP Deploy
    #   uses: SamKirkland/FTP-Deploy-Action@3.1.0
    #   with:
    #     ftp-server: ${{ secrets.ONE_EQUALITY_SERVER }}
    #     ftp-username: ${{ secrets.ONE_EQUALITY_USERNAME }}
    #     ftp-password: ${{ secrets.ONE_EQUALITY_PASSWORD }}
    #     local-dir: ./public_html/